services:
  app:

    build:
      context: .
      target: ${STAGE}
      dockerfile: Dockerfile
      args:
        - ${APP_VERSION}

    image: jsantamv/teslo-shop-backend:1.1.1
    container_name: nest-app
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_VERSION: ${APP_VERSION}
      STAGE: ${STAGE}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      PORT: ${PORT}
      HOST_API: ${HOST_API}
      JWT_SECRET: ${JWT_SECRET}

  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: ${DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
    external: false

#COMANDO PARA RODAR O DOCKER-COMPOSE PRODUTION
#docker-compose -f docker-compose.prod.yml up

# PARA EL BUILD
#docker-compose -f docker-compose.prod.yml build

#DOCKER HUB
# Creo el builder para hacer el buildx
#docker buildx create --name my-build --use
#docker buildx ls


#docker buildx build --platform linux/amd64 -t jsantamv/teslo-shop-backend:1.0.1 .
#docker buildx build --platform linux/arm64 -t jsantamv/teslo-shop-backend:1.0.1 .

#push
# EL COMANDO SIGUIENTE ES PARA HACER EL PUSH DE LA IMAGEN LOCAL PARA LUEGO SUBIRLA AL DOCKER HUB
#docker buildx build --platform linux/amd64,linux/arm64 -t jsantamv/teslo-shop-backend:1.0.1 --push .

# PARA SUBIR LA IMAGEN AL DOCKER HUB
#docker login
#docker push jsantamv/teslo-shop-backend:1.0.1