apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  # Base64 String:  Chirripo3820 = cG9zdGdyZXM=
  # echo -n postgres | base64
  # Chirripo3820
  JWT_SECRET: Q2hpcnJpcG8yODIw