apiVersion: v1
kind: Secret
metadata:
  name: pg-admin-secret
type: Opaque
data:
  #base64 String: se debe de convertir: Pg-admin: superman@google.com
  PG_ADMIN_EMAIL: c3VwZXJtYW5AZ29vZ2xlLmNvbQ==

  #base64 String: se debe de convertir: cerro alto
  DB_PASSWORD: Q2hpcnJpcG8zODIwQA==


# COMANDOS DE LINUX PARA CONVERTIR A BASE64
#echo -n postgres | base64
