apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  #base64 string: se debe de convertir: postgres
  DB_USER: cG9zdGdyZXM=

  #base64 string: se debe de convertir: cerro alto
  DB_PASSWORD: Q2hpcnJpcG8zODIwQA==


# COMANDOS DE LINUX PARA CONVERTIR A BASE64
#echo -n postgres | base64
