
# FROM --platform=linux/arm64 node:19.2-alpine3.16
#FROM --platform=$BUILDPLATFORM node:19.2-alpine3.16
FROM node:19.2-alpine3.16
#RUN echo "I am running on $BUILDPLATFORM, building for $TARGETPLATFORM" > /log

# /work directory
# cd app
WORKDIR /app

# destino /app path relativo al WORKDIR
COPY package.json ./

# installar las dependencias
RUN npm install





COPY . .

# Realizar la prueba
RUN npm run test

# Eliminar files no necesarios en prod
# esto no esta mal, pero podemos dejar por fuera otros directorios o archivos
RUN rm -rf test && rm -rf node_modules

# unicamente las depd de prod
RUN npm install --prod

#Ejecutar aplicacion
CMD ["node", "app.js"]
